### ISSUE TITLE
Open and close sounds played twice

### ISSUE THREAD

**Issue by Merthew** [lMartin3/BetterShulkerBoxesRewritten#17] opened 2022-04-27 03:41 UTC
As the title says, when opening a shulker box in my inventory the open and close sounds get played twice. Also when changing the open and close sounds it plays the selected one as well as the default one.

It would be nice to be able to turn off the sounds all together.

**Comment by lMartin3** [comment] 2022-04-27 12:33
Hey, I just tried to replicate this bug on my test server using Better Shulker Boxes 3.1.1 and the latest  paper build, and I was not able to reproduce it. Nonetheless I have added the feature to disable sounds by just leaving empty strings, which will be released in 3.1.2
```yaml
open_sound: ''
close_sound: ''
```

If you can, please reply with your plugin version number and server software (spigot/paper, which mc version and which build number).

**Comment by Merthew** [comment] 2022-04-27 19:45
I am running 
BSB v3.1.3
Paper version git-Paper-290 (MC: 1.18.2)
And minecraft 1.18.2

**Comment by Merthew** [comment] 2022-04-27 19:55
Updating to the newest version of paper hasn't changed the issue, it still plays the sounds twice.

**Comment by lMartin3** [comment] 2022-04-29 02:20
I have attempted to reproduce this bug but I was not able to do so. The plugin only sends a single sound packet, I've checked through proxy and the debug menu. Please try using another client or setting up a test server, otherwise send me your server IP and I might be able to figure out what's wrong.

**Comment by lMartin3** [comment] 2022-09-03 04:08
Issue closed due to inactivity and inability to reproduce the bug, reopen if necessary.

**Closed by lMartin3** 2022-09-03 04:08 UTC
Labels: help wanted
