### ISSUE TITLE
Config doesn't work?

### ISSUE THREAD

**Issue by RhinoCD** [lMartin3/BetterShulkerBoxesRewritten#19] opened 2022-05-27 00:55 UTC
The messages in config works fine, however the option to enable / disable things like right click in inventory / right click in hand true / false doesn't work. For me, it just allows players to open it any way even though in the config it says false. 

`cooldown: 0 # Integer - Time a player has to wait between uses of the plugin's features, set to 0 to disable
requires_permission: true # Boolean - Set this to false if you want to allow anyone to use the plugin
enable_read_only: false # Boolean - Set this to true if you just want players to be able to preview a shulkerbox's contents
enable_right_click_open: false # Boolean - Set this to false if you do not want to allow players to open a shulker by rightclicking
enable_inventory_click_open: false # Boolean - Set this to false if you do not want to allow players to open a shulker by shift clicking in their inventories
disable_movement_check: false # Boolean - Set this to true if you want players to be able to open shulkerboxes using the plugin while moving`

**Comment by lMartin3** [comment] 2022-05-27 23:37
Duplicate of #16, already fixed in developmental builds, will be released in `3.1.4`

**Closed by lMartin3** 2022-05-27 23:37 UTC
Labels: duplicate
